### ISSUE TITLE
Please add for German users: Amazon Prime Video and SkyTicket

### ISSUE THREAD

**Issue by JaypeeM** [arbitrarydot/testube#14]
Hi,

Please add for German users: 

Amazon Prime Video (https://www.amazon.de/Amazon-Video/b/?ie=UTF8&node=3010075031)

and 

SkyTicket (www.https://skyticket.sky.de/watch/home)

thanks

**Comment by JaxonWright** [comment]
Prime Video does not support Chromium, which is the only reason that isn't included.

**Comment by JaxonWright** [comment]
Prime Video did get added, but I am not sure if it actually works in the Tesla browser
