### ISSUE TITLE
Geforce Now - Your Device is Unsupported

### ISSUE THREAD

**Issue by fotiDim** [arbitrarydot/testube#20]
Trying to open Geforce Now I immediately get an error. Is there any workaround to make it work?

![C7F1F9CF-F494-4996-9833-1D043253A347](https://user-images.githubusercontent.com/2326415/102693434-d3819580-421a-11eb-8fc1-3b639f68ffd0.jpeg)

**Comment by JaxonWright** [comment]
That's unfortunate. I do not have control over what the other sites support.
