### ISSUE TITLE
'Show in full screen' not displaying in new model Y

### ISSUE THREAD

**Issue by gheldean** [arbitrarydot/testube#26]
I have been using your app for a long time in my 2018 Model 3 with no issues (it's amaizing....).

I got a new Model Y this week (with Ryzen processor, if important), and when I go to testube.app, the show in full screen button is no longer displaying at the bottom.

Please let me know what additional details may be helpful to resolve

**Comment by JaxonWright** [comment]
I am seeing this after my 2018 Model 3 just updated. Fixing now!

**Comment by JaxonWright** [comment]
For future reference, clicking the build hash at the bottom middle of the screen, copying the user agent, and pasting it in an issue will help me diagnose this sooner. Otherwise we're usually at the whim of my own car.
