### ISSUE TITLE
Problem getting to full screen mode/request for full screen button

### ISSUE THREAD

**Issue by feickoo** [arbitrarydot/testube#27]
After the update, full screen pop up no long appear any more.
Can you add a full screen button?

**Comment by JaxonWright** [comment]
I will have to take a look at this tonight. What version is your car on, by chance?

Clicking the build hash at the bottom middle of the screen, copying the user agent, and pasting it in this issue will help me diagnose this sooner. Otherwise, we're usually at the whim of my own car.

**Comment by JaxonWright** [comment]
Looks like you are probably on the FSD Beta software. I just checked in my own Model 3 which does have FSD Beta and it was not recognized.

Here is the UserAgent for reference. I also need to make it easier to copy this dang thing haha.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Tesla/terminal-das-fsd-eap-10-12-2-17-cfe1aeaefb`

**Comment by JaxonWright** [comment]
@feickoo all fixed up!

**Comment by feickoo** [comment]
Oh wow, this is fast.
Thank you so much
You are the best

**Comment by feickoo** [comment]
Well, I still cannot use full screen mode.
I just checked my version.
It's v11.0 (2022.12.3.7.5 258d28b371d8)
Is it the one you updated?

**Comment by JaxonWright** [comment]
@feickoo should be fixed for the version you are on. It failed because of the extra decimal over what is usual. Thanks for the help!

**Comment by feickoo** [comment]
Well, sorry to bother you again 😔
But I just tried it again and it doesn't seem to work.

**Comment by feickoo** [comment]
I have updated the car again and it's working now. Thanks for your help.
