### ISSUE TITLE
Resolution adjustment 

### ISSUE THREAD

**Issue by feickoo** [arbitrarydot/testube#29]
After the update, the interface has become larger due to resolution change. It results the interface became awkwardly small and leaves a big blank bottom.

Maybe you can implement RWD into it?

**Comment by JaxonWright** [comment]
I'm not sure what you are referring to. Could you provide a picture of your screen here for an example?

**Comment by feickoo** [comment]
Here are the pic and vid
https://photos.app.goo.gl/oJRDhV4BuVDwqgkt8
