### ISSUE TITLE
Fullscreen Notification not showing

### ISSUE THREAD

**Issue by DwieDave** [arbitrarydot/testube#30]
Hi,

i've updated my Model 3 to 2022.16.3 today and wanted to test the browser performance with testube but the Fullscreen toast notification did not show up and therefore apps like A better Routeplanner did not load in Fullscreen.

Is there a known bug at the moment?

Regards

**Comment by JaxonWright** [comment]
Hello @DwieDave, 

Could you please:

1) Click on the build hash in the bottom middle of the screen.  (Where the fullscreen notification usually is)
![image](https://user-images.githubusercontent.com/14099593/174623695-a5125eb1-a40c-40fd-b480-670c9c543e1f.png)

2) Click the copy button on the end of the UserAgent field, and paste it in here?    
![image](https://user-images.githubusercontent.com/14099593/174623883-454666fc-f817-42db-a2da-33d2b2ee9504.png)

I am on the FSD beta, so I can only go make sure it works on my software and its hard to test other configs without knowing that information.

Thanks

**Comment by JaxonWright** [comment]
Related to #27

**Comment by DwieDave** [comment]
The build shown is from June 20
(Hash fafc18a) 
I really dont know how to paste from the tesla (is it even possible?)

I've taken a picture and used OCR:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Tesla/feature-2022.16.3-391-cedf22462e
```

**Comment by JaxonWright** [comment]
> I really dont know how to paste from the tesla (is it even possible?)

I think you can just long-press in a text area. I guess I should try it before telling people to do it haha.

Thanks for going above and beyond. I'll look into fixing it tonight!

**Comment by DwieDave** [comment]
I've tried the iOS tap and hold gesture in every possible way and nothing showed up.
Thanks for the fast reply.

Just out of curiosity: Why do you show the SnackBar only in a Tesla Browser?

**Comment by DwieDave** [comment]
Thanks for your fast update!
The Snackbar is now showing and fullscreen mode is working but now I have another bug (issue #33).
