### ISSUE TITLE
HTML Zoom wrong when in Fullscreen mode

### ISSUE THREAD

**Issue by DwieDave** [arbitrarydot/testube#33]
Hello,
I'm on firmware 2022.16.3 and when I enter fullscreen mode my Zoom level is way too far zoomed out:

![image](https://user-images.githubusercontent.com/15933094/178434973-571a53ce-bf29-40ae-92ea-cb2a076e0784.jpeg)

I changed the HTML zoom setting yesterday to capture the userAgent for issue #30 
And now its set to this zoom level (< 1 [I believe it was 0.64ish]) every time I start fullscreen mode.
When I correct the zoom level (1 to 1.2?) everything looks good for the session until I restart into fullscreen mode.

In the normal browser mode i cannot click the build hash to adjust the zoom apparently because of the snack bar.

Regards
DwieDave

**Comment by JaxonWright** [comment]
Must be the same as #29. Thanks for the picture

**Comment by JaxonWright** [comment]
Should be good to go now. The HTML zoom stuff seems to only be needed on the FSD builds now.

**Comment by JaxonWright** [comment]
> In the normal browser mode i cannot click the build hash to adjust the zoom apparently because of the snack bar.

Fixed this as well

**Comment by DwieDave** [comment]
I can confirm that everything (zoom, snackbar & debug menu) now works as expected in my Browser 👍🏻

Thank you very much!
