### ISSUE TITLE
Docker container support

### ISSUE THREAD

**Issue by nylonee** [arbitrarydot/testube#38]
It'd be great to be able to host a self-contained version of this, the easiest way would be to package this as a docker container.

I think the best kinda container would also have the ability to turn on/off apps, as in #2.

**Comment by JaxonWright** [comment]
Sounds a little bit like over-engineering to me. If you want to host it yourself, you can do so however you want already.

That said, if you want #2 added, nothing is stopping anyone from making a PR to make it possible. I do plan on working more on testube at some point, though.
