### ISSUE TITLE
No full-screen button

### ISSUE THREAD

**Issue by jschroebel** [arbitrarydot/testube#40]
I am not getting the full-screen button on my Model Y, nor am I seeing a “report Tesla detection issue” button.
![image](https://github.com/arbitrarydot/testube/assets/85417095/88eebb10-b0bf-41c3-b353-6bc3c3b6ad1e)

**Comment by orichienal** [comment]
Since my Model Y has the software version 2023.26.7, I no longer see the full-screen overlay at the bottom.
The device info is the same for me and the viewports are also the same.
if more info is needed then just let me know.

Greetings and thanks

**Comment by JaxonWright** [comment]
Please refer to #31. Click the Report Tesla Detection Issue button on the page you took a picture of

**Comment by orichienal** [comment]
just pressed it, maybe even twice 😅

**Comment by JaxonWright** [comment]
So it turns out that Tesla no longer puts information in the UserAgent that tells you the browser is in a Tesla. Because of this, I decided to not try to make sure the client is a Tesla and just show the snackbar for everyone unless coming from YouTube (aka you are in fullscreen mode now)
