### ISSUE TITLE
URL redirects do not trigger

### ISSUE THREAD

**Issue by andrewstrother** [arbitrarydot/testube#42]
for example, entering “f1tv.com” as a custom URL will not work, as that redirects to “f1tv.formula1.com”. Entering the latter and accessing directly works just fine, but the shorter URL will not redirect.

**Comment by JaxonWright** [comment]
The actual problem here is that "f1tv.com" is not served over https, which testube is forcing the URL to start with. I suppose I could drop that behavior.
